languages:
  Ruby: true
exclude_paths:
- "README.md"
- "Gemfile"
- "Gemfile.lock"
- ".travis.yml"
- "config.ru"
- ".gitignore"
engines:
  csslint:
    enabled: true
    checks:
      qualified-headings:
        enabled: false
